spring:
  
  application:
    name: auth-service

    profiles: { active: dev }
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/user
    username: postgres
    password: bj151197
  keycloak:

    client-id: auth-client
    client-secret: secret123
    server-url: http://localhost:8080/auth
    realm: master


  dotenv:
    enabled: true

  spring:
  cloud:
    config:
      enabled: false  